export const textStyles = {
  title: {
    fontFamily: 'title',
    fontWeight: '200',
    fontSize: 'xl',
    letterSpacing: '2px',
    lineHeight: '100%',
    textDecoration: 'none',
    textTransform: 'none',
  },
  subtitle: {
    fontFamily: 'subtitle',
    fontWeight: '400',
    fontSize: 'md',
    letterSpacing: '0',
    lineHeight: '100%',
    textDecoration: 'none',
    textTransform: 'none',
  },
  heading: {
    fontFamily: 'heading',
    fontWeight: '500',
    fontSize: 'lg',
    letterSpacing: '1px',
    lineHeight: '100%',
    textDecoration: 'none',
    textTransform: 'none',
  },
  subheading: {
    fontFamily: 'subheading',
    fontWeight: '600',
    fontSize: 'md',
    lineHeight: '100%',
    letterSpacing: '1px',
    textDecoration: 'none',
    textTransform: 'none',
  },
  body: {
    fontFamily: 'body',
    fontWeight: '500',
    fontSize: 'sm',
    lineHeight: [null, '166%', '162%', '158%', '154%', '150%'],
    letterSpacing: '1px',
    textDecoration: 'none',
    textTransform: 'none',
  },
  caption: {
    fontFamily: 'caption',
    fontWeight: 600,
    fontSize: 'xs',
    lineHeight: [null, null, '166%', '162%', '158%', '154%'],
    letterSpacing: 'wide',
    textDecoration: 'none',
    textTransform: 'uppercase',
  },
  mono: {
    fontFamily: 'mono',
    fontWeight: 'normal',
    fontSize: 'sm',
    lineHeight: [null, '166%', '162%', '158%', '154%', '150%'],
    letterSpacing: '0',
    textDecoration: 'none',
    textTransform: 'none',
  },
  button: {
    fontFamily: 'heading',
    // (fontWeight is determined by button size)
    // (fontSize is determined by button size)
    lineHeight: '100%',
    letterSpacing: '0.02rem',
    textDecoration: 'none',
    textTransform: 'none',
  },
};
