export const textStyles = {
  title: {
    fontFamily: 'title',
    fontWeight: '400',
    fontSize: ['2xl', '2xl', '3xl', '3xl', '4xl', '4xl'],
    letterSpacing: '0',
    lineHeight: '100%',
    textDecoration: 'none',
    textTransform: 'none',
  },
  subtitle: {
    fontFamily: 'subtitle',
    fontWeight: '400',
    fontSize: ['lg', 'lg', 'xl', 'xl', '2xl', '2xl'],
    letterSpacing: '0',
    lineHeight: '100%',
    textDecoration: 'none',
    textTransform: 'none',
  },
  heading: {
    fontFamily: 'heading',
    fontWeight: [null, 'semibold', 'regular'],
    fontSize: ['md', 'md', 'lg', 'lg', 'xl', 'xl'],
    letterSpacing: '0',
    lineHeight: '100%',
    textDecoration: 'none',
    textTransform: 'none',
  },
  subheading: {
    fontFamily: 'subheading',
    fontWeight: [null, 'semibold', 'regular'],
    fontSize: ['sm', 'sm', 'md', 'md', 'lg', 'lg'],
    lineHeight: '100%',
    letterSpacing: '0',
    textDecoration: 'none',
    textTransform: 'none',
  },
  body: {
    fontFamily: 'body',
    fontWeight: 'normal',
    fontSize: ['sm', 'sm', 'md', 'md', 'lg', 'lg'],
    lineHeight: [null, '166%', '162%', '158%', '154%', '150%'],
    letterSpacing: '0',
    textDecoration: 'none',
    textTransform: 'none',
  },
  caption: {
    fontFamily: 'caption',
    fontWeight: 600,
    fontSize: ['xs', null, null, null, 'sm', 'sm'],
    lineHeight: [null, null, '166%', '162%', '158%', '154%'],
    letterSpacing: 'wide',
    textDecoration: 'none',
    textTransform: 'uppercase',
  },
  mono: {
    fontFamily: 'mono',
    fontWeight: 'normal',
    fontSize: ['sm', 'sm', 'md', 'md', 'lg', 'lg'],
    lineHeight: [null, '166%', '162%', '158%', '154%', '150%'],
    letterSpacing: '0',
    textDecoration: 'none',
    textTransform: 'none',
  },
  button: {
    fontFamily: 'heading',
    // (fontWeight is determined by button size)
    // (fontSize is determined by button size)
    lineHeight: '100%',
    letterSpacing: '0.02rem',
    textDecoration: 'none',
    textTransform: 'none',
  },
};
